import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    // ROMÂNĂ
    'ro': {
      'app_name': 'DatingX',
      'welcome': 'Bine ai venit',
      'login': 'Autentificare',
      'register': 'Înregistrare',
      'email': 'Email',
      'password': 'Parolă',
      'confirm_password': 'Confirmă parola',
      'forgot_password': 'Ai uitat parola?',
      'dont_have_account': 'Nu ai cont?',
      'already_have_account': 'Ai deja cont?',
      'search': 'Caută',
      'discover': 'Descoperă',
      'favorites': 'Compatibilitățile tale',
      'messages': 'Mesajele tale',
      'profile': 'Profil',
      'edit_profile': 'Editează profilul',
      'logout': 'Deconectare',
      'save': 'Salvează',
      'cancel': 'Anulează',
      'delete': 'Șterge',
      'send': 'Trimite',
      'search_perfect_match': 'Caută perechea perfectă',
      'looking_for': 'Caut',
      'age': 'Vârsta',
      'years': 'ani',
      'relationship_type': 'Ce tip de relație cauți?',
      'country': 'Țara',
      'city': 'Orașul',
      'interests': 'Interese Comune',
      'advanced_search': '+ Căutare Detaliată (opțional)',
      'hide_advanced': 'Ascunde Căutare Detaliată',
      'optional_criteria': 'Criterii Opționale',
      'height': 'Înălțime',
      'height_cm': 'Înălțime (cm)',
      'from': 'De la',
      'to': 'Până la',
      'has_children': 'Are copii?',
      'wants_children': 'Dorește copii?',
      'education': 'Educație',
      'smoking': 'Fumător?',
      'drinking': 'Consumă alcool?',
      'religion': 'Religie',
      'languages': 'Limbi vorbite',
      'body_type': 'Tipul corpului',
      'relationship_status': 'Status relație',
      'post_ad': 'Adaugă anunț',
      'my_ads': 'Anunțurile mele',
      'title': 'Titlu',
      'description': 'Descriere',
      'name': 'Nume',
      'phone': 'Telefon',
      'photos': 'Poze',
      'add_photos': 'Adaugă poze',
      'select_gender': 'Selectează genul',
      'select_relationship_type': 'Selectează tipul de relație',
      'male': 'Bărbat',
      'female': 'Femeie',
      'non_binary': 'Non-binar',
      'yes': 'Da',
      'no': 'Nu',
      'maybe': 'Poate',
      'already_have': 'Deja am',
      'prefer_not_say': 'Prefer să nu spun',
      'high_school': 'Liceu',
      'college': 'Facultate',
      'masters': 'Masterat',
      'phd': 'Doctorat',
      'other': 'Altele',
      'occasionally': 'Ocazional',
      'no_consume': 'Nu consum',
      'socially': 'Social',
      'frequently': 'Frecvent',
      'athletic': 'Athletic',
      'slim': 'Slim',
      'average': 'Average',
      'curvy': 'Curvy',
      'plus_size': 'Plus Size',
      'single': 'Necăsătorit(ă)',
      'divorced': 'Divorțat(ă)',
      'widowed': 'Văduv(ă)',
      'orthodox': 'Creștin-Ortodox',
      'catholic': 'Catolic',
      'protestant': 'Protestant',
      'muslim': 'Muslim',
      'buddhist': 'Budist',
      'atheist': 'Ateu',
      'agnostic': 'Agnostic',
      'change_language': 'Schimbă limba',
      'language': 'Limba',
      'romanian': 'Română',
      'english': 'Engleză',
      'french': 'Franceză',
      'german': 'Germană',
      'spanish': 'Spaniolă',
      'italian': 'Italiană',
      'russian': 'Rusă',
      'hungarian': 'Maghiară',
      'post_matrimonial_ad': 'Publică Anunț Matrimonial',
      'my_ads_title': 'Anunțurile Mele',
      'ads_posted': 'anunțuri postate',
      'ad_posted': 'anunț postat',
      'no_ads_yet': 'Nu ai anunțuri postate încă',
      'post_first_ad': 'Postează primul tău anunț pentru a găsi perechea perfectă!',
      'post_new_ad': 'Postează Anunț Nou',
      'find_match': 'Caută Perechea Potrivită',
      'perfect_match_description': 'Găsește persoana care ți se potrivește perfect bazat pe compatibilitate reală',
      'login_register': 'Conectare / Înregistrare',
      'no_favorites': 'Niciun anunț salvat',
      'save_favorites': 'Salvează anunțurile care te interesează',
      'no_messages': 'Nicio conversație',
      'start_messaging': 'Trimite un mesaj pentru a începe o conversație',
      'unread': 'necitit',
      'unread_plural': 'necitite',
    },
    
    // ENGLISH
    'en': {
      'app_name': 'DatingX',
      'welcome': 'Welcome',
      'login': 'Login',
      'register': 'Register',
      'email': 'Email',
      'password': 'Password',
      'confirm_password': 'Confirm password',
      'forgot_password': 'Forgot password?',
      'dont_have_account': "Don't have an account?",
      'already_have_account': 'Already have an account?',
      'search': 'Search',
      'discover': 'Discover',
      'favorites': 'Your Matches',
      'messages': 'Your Messages',
      'profile': 'Profile',
      'edit_profile': 'Edit profile',
      'logout': 'Logout',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'send': 'Send',
      'search_perfect_match': 'Find your perfect match',
      'looking_for': 'Looking for',
      'age': 'Age',
      'years': 'years',
      'relationship_type': 'What type of relationship are you looking for?',
      'country': 'Country',
      'city': 'City',
      'interests': 'Common Interests',
      'advanced_search': '+ Advanced Search (optional)',
      'hide_advanced': 'Hide Advanced Search',
      'optional_criteria': 'Optional Criteria',
      'height': 'Height',
      'height_cm': 'Height (cm)',
      'from': 'From',
      'to': 'To',
      'has_children': 'Has children?',
      'wants_children': 'Wants children?',
      'education': 'Education',
      'smoking': 'Smoking?',
      'drinking': 'Drinking?',
      'religion': 'Religion',
      'languages': 'Languages spoken',
      'body_type': 'Body type',
      'relationship_status': 'Relationship status',
      'post_ad': 'Post ad',
      'my_ads': 'My ads',
      'title': 'Title',
      'description': 'Description',
      'name': 'Name',
      'phone': 'Phone',
      'photos': 'Photos',
      'add_photos': 'Add photos',
      'select_gender': 'Select gender',
      'select_relationship_type': 'Select relationship type',
      'male': 'Male',
      'female': 'Female',
      'non_binary': 'Non-binary',
      'yes': 'Yes',
      'no': 'No',
      'maybe': 'Maybe',
      'already_have': 'Already have',
      'prefer_not_say': 'Prefer not to say',
      'high_school': 'High School',
      'college': 'College',
      'masters': 'Masters',
      'phd': 'PhD',
      'other': 'Other',
      'occasionally': 'Occasionally',
      'no_consume': 'Do not consume',
      'socially': 'Socially',
      'frequently': 'Frequently',
      'athletic': 'Athletic',
      'slim': 'Slim',
      'average': 'Average',
      'curvy': 'Curvy',
      'plus_size': 'Plus Size',
      'single': 'Single',
      'divorced': 'Divorced',
      'widowed': 'Widowed',
      'orthodox': 'Orthodox',
      'catholic': 'Catholic',
      'protestant': 'Protestant',
      'muslim': 'Muslim',
      'buddhist': 'Buddhist',
      'atheist': 'Atheist',
      'agnostic': 'Agnostic',
      'change_language': 'Change language',
      'language': 'Language',
      'romanian': 'Romanian',
      'english': 'English',
      'french': 'French',
      'german': 'German',
      'spanish': 'Spanish',
      'italian': 'Italian',
      'russian': 'Russian',
      'hungarian': 'Hungarian',
      'post_matrimonial_ad': 'Post Matrimonial Ad',
      'my_ads_title': 'My Ads',
      'ads_posted': 'ads posted',
      'ad_posted': 'ad posted',
      'no_ads_yet': 'No ads posted yet',
      'post_first_ad': 'Post your first ad to find your perfect match!',
      'post_new_ad': 'Post New Ad',
      'find_match': 'Find Your Match',
      'perfect_match_description': 'Find the person who perfectly matches you based on real compatibility',
      'login_register': 'Login / Register',
      'no_favorites': 'No saved ads',
      'save_favorites': 'Save ads that interest you',
      'no_messages': 'No conversations',
      'start_messaging': 'Send a message to start a conversation',
      'unread': 'unread',
      'unread_plural': 'unread',
    },

    // FRANÇAIS
    'fr': {
      'app_name': 'DatingX',
      'welcome': 'Bienvenue',
      'login': 'Connexion',
      'register': 'S\'inscrire',
      'email': 'Email',
      'password': 'Mot de passe',
      'confirm_password': 'Confirmer le mot de passe',
      'forgot_password': 'Mot de passe oublié?',
      'dont_have_account': 'Pas de compte?',
      'already_have_account': 'Vous avez déjà un compte?',
      'search': 'Rechercher',
      'discover': 'Découvrir',
      'favorites': 'Vos Compatibilités',
      'messages': 'Vos Messages',
      'profile': 'Profil',
      'edit_profile': 'Modifier le profil',
      'logout': 'Déconnexion',
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'delete': 'Supprimer',
      'send': 'Envoyer',
      'search_perfect_match': 'Trouvez votre partenaire idéal',
      'looking_for': 'Je cherche',
      'age': 'Âge',
      'years': 'ans',
      'relationship_type': 'Quel type de relation recherchez-vous?',
      'country': 'Pays',
      'city': 'Ville',
      'interests': 'Intérêts communs',
      'advanced_search': '+ Recherche Avancée (optionnel)',
      'hide_advanced': 'Masquer Recherche Avancée',
      'optional_criteria': 'Critères Optionnels',
      'height': 'Taille',
      'height_cm': 'Taille (cm)',
      'from': 'De',
      'to': 'À',
      'has_children': 'A des enfants?',
      'wants_children': 'Veut des enfants?',
      'education': 'Éducation',
      'smoking': 'Fumeur?',
      'drinking': 'Boit de l\'alcool?',
      'religion': 'Religion',
      'languages': 'Langues parlées',
      'body_type': 'Type de corps',
      'relationship_status': 'Statut relationnel',
      'post_ad': 'Publier une annonce',
      'my_ads': 'Mes annonces',
      'title': 'Titre',
      'description': 'Description',
      'name': 'Nom',
      'phone': 'Téléphone',
      'photos': 'Photos',
      'add_photos': 'Ajouter des photos',
      'select_gender': 'Sélectionner le genre',
      'select_relationship_type': 'Sélectionner le type de relation',
      'male': 'Homme',
      'female': 'Femme',
      'non_binary': 'Non-binaire',
      'yes': 'Oui',
      'no': 'Non',
      'maybe': 'Peut-être',
      'already_have': 'J\'en ai déjà',
      'prefer_not_say': 'Préfère ne pas dire',
      'high_school': 'Lycée',
      'college': 'Université',
      'masters': 'Master',
      'phd': 'Doctorat',
      'other': 'Autre',
      'occasionally': 'Occasionnellement',
      'no_consume': 'Ne consomme pas',
      'socially': 'Socialement',
      'frequently': 'Fréquemment',
      'athletic': 'Athlétique',
      'slim': 'Mince',
      'average': 'Moyen',
      'curvy': 'Avec des formes',
      'plus_size': 'Grande taille',
      'single': 'Célibataire',
      'divorced': 'Divorcé(e)',
      'widowed': 'Veuf/Veuve',
      'orthodox': 'Orthodoxe',
      'catholic': 'Catholique',
      'protestant': 'Protestant',
      'muslim': 'Musulman',
      'buddhist': 'Bouddhiste',
      'atheist': 'Athée',
      'agnostic': 'Agnostique',
      'change_language': 'Changer de langue',
      'language': 'Langue',
      'romanian': 'Roumain',
      'english': 'Anglais',
      'french': 'Français',
      'german': 'Allemand',
      'spanish': 'Espagnol',
      'italian': 'Italien',
      'russian': 'Russe',
      'hungarian': 'Hongrois',
      'post_matrimonial_ad': 'Publier une Annonce',
      'my_ads_title': 'Mes Annonces',
      'ads_posted': 'annonces publiées',
      'ad_posted': 'annonce publiée',
      'no_ads_yet': 'Aucune annonce publiée',
      'post_first_ad': 'Publiez votre première annonce pour trouver votre partenaire idéal!',
      'post_new_ad': 'Publier une Nouvelle Annonce',
      'find_match': 'Trouver Votre Partenaire',
      'perfect_match_description': 'Trouvez la personne qui vous correspond parfaitement basé sur une compatibilité réelle',
      'login_register': 'Connexion / Inscription',
      'no_favorites': 'Aucune annonce sauvegardée',
      'save_favorites': 'Sauvegardez les annonces qui vous intéressent',
      'no_messages': 'Aucune conversation',
      'start_messaging': 'Envoyez un message pour commencer une conversation',
      'unread': 'non lu',
      'unread_plural': 'non lus',
    },

    // DEUTSCH
    'de': {
      'app_name': 'DatingX',
      'welcome': 'Willkommen',
      'login': 'Anmelden',
      'register': 'Registrieren',
      'email': 'E-Mail',
      'password': 'Passwort',
      'confirm_password': 'Passwort bestätigen',
      'forgot_password': 'Passwort vergessen?',
      'dont_have_account': 'Kein Konto?',
      'already_have_account': 'Haben Sie bereits ein Konto?',
      'search': 'Suchen',
      'discover': 'Entdecken',
      'favorites': 'Ihre Übereinstimmungen',
      'messages': 'Ihre Nachrichten',
      'profile': 'Profil',
      'edit_profile': 'Profil bearbeiten',
      'logout': 'Abmelden',
      'save': 'Speichern',
      'cancel': 'Abbrechen',
      'delete': 'Löschen',
      'send': 'Senden',
      'search_perfect_match': 'Finden Sie Ihren perfekten Partner',
      'looking_for': 'Suche nach',
      'age': 'Alter',
      'years': 'Jahre',
      'relationship_type': 'Welche Art von Beziehung suchen Sie?',
      'country': 'Land',
      'city': 'Stadt',
      'interests': 'Gemeinsame Interessen',
      'advanced_search': '+ Erweiterte Suche (optional)',
      'hide_advanced': 'Erweiterte Suche ausblenden',
      'optional_criteria': 'Optionale Kriterien',
      'height': 'Größe',
      'height_cm': 'Größe (cm)',
      'from': 'Von',
      'to': 'Bis',
      'has_children': 'Hat Kinder?',
      'wants_children': 'Möchte Kinder?',
      'education': 'Bildung',
      'smoking': 'Raucher?',
      'drinking': 'Trinkt Alkohol?',
      'religion': 'Religion',
      'languages': 'Gesprochene Sprachen',
      'body_type': 'Körpertyp',
      'relationship_status': 'Beziehungsstatus',
      'post_ad': 'Anzeige veröffentlichen',
      'my_ads': 'Meine Anzeigen',
      'title': 'Titel',
      'description': 'Beschreibung',
      'name': 'Name',
      'phone': 'Telefon',
      'photos': 'Fotos',
      'add_photos': 'Fotos hinzufügen',
      'select_gender': 'Geschlecht auswählen',
      'select_relationship_type': 'Beziehungstyp auswählen',
      'male': 'Mann',
      'female': 'Frau',
      'non_binary': 'Nicht-binär',
      'yes': 'Ja',
      'no': 'Nein',
      'maybe': 'Vielleicht',
      'already_have': 'Habe bereits',
      'prefer_not_say': 'Möchte ich nicht sagen',
      'high_school': 'Gymnasium',
      'college': 'Hochschule',
      'masters': 'Master',
      'phd': 'Promotion',
      'other': 'Andere',
      'occasionally': 'Gelegentlich',
      'no_consume': 'Konsumiere nicht',
      'socially': 'Sozial',
      'frequently': 'Häufig',
      'athletic': 'Athletisch',
      'slim': 'Schlank',
      'average': 'Durchschnittlich',
      'curvy': 'Kurvig',
      'plus_size': 'Große Größe',
      'single': 'Single',
      'divorced': 'Geschieden',
      'widowed': 'Verwitwet',
      'orthodox': 'Orthodox',
      'catholic': 'Katholisch',
      'protestant': 'Protestantisch',
      'muslim': 'Muslimisch',
      'buddhist': 'Buddhistisch',
      'atheist': 'Atheist',
      'agnostic': 'Agnostiker',
      'change_language': 'Sprache ändern',
      'language': 'Sprache',
      'romanian': 'Rumänisch',
      'english': 'Englisch',
      'french': 'Französisch',
      'german': 'Deutsch',
      'spanish': 'Spanisch',
      'italian': 'Italienisch',
      'russian': 'Russisch',
      'hungarian': 'Ungarisch',
      'post_matrimonial_ad': 'Anzeige Veröffentlichen',
      'my_ads_title': 'Meine Anzeigen',
      'ads_posted': 'Anzeigen veröffentlicht',
      'ad_posted': 'Anzeige veröffentlicht',
      'no_ads_yet': 'Noch keine Anzeigen veröffentlicht',
      'post_first_ad': 'Veröffentlichen Sie Ihre erste Anzeige, um Ihren perfekten Partner zu finden!',
      'post_new_ad': 'Neue Anzeige Veröffentlichen',
      'find_match': 'Finden Sie Ihren Partner',
      'perfect_match_description': 'Finden Sie die Person, die perfekt zu Ihnen passt, basierend auf echter Kompatibilität',
      'login_register': 'Anmelden / Registrieren',
      'no_favorites': 'Keine gespeicherten Anzeigen',
      'save_favorites': 'Speichern Sie Anzeigen, die Sie interessieren',
      'no_messages': 'Keine Gespräche',
      'start_messaging': 'Senden Sie eine Nachricht, um ein Gespräch zu beginnen',
      'unread': 'ungelesen',
      'unread_plural': 'ungelesen',
    },

    // ESPAÑOL
    'es': {
      'app_name': 'DatingX',
      'welcome': 'Bienvenido',
      'login': 'Iniciar sesión',
      'register': 'Registrarse',
      'email': 'Correo electrónico',
      'password': 'Contraseña',
      'confirm_password': 'Confirmar contraseña',
      'forgot_password': '¿Olvidaste tu contraseña?',
      'dont_have_account': '¿No tienes cuenta?',
      'already_have_account': '¿Ya tienes una cuenta?',
      'search': 'Buscar',
      'discover': 'Descubrir',
      'favorites': 'Tus Compatibilidades',
      'messages': 'Tus Mensajes',
      'profile': 'Perfil',
      'edit_profile': 'Editar perfil',
      'logout': 'Cerrar sesión',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'delete': 'Eliminar',
      'send': 'Enviar',
      'search_perfect_match': 'Encuentra tu pareja perfecta',
      'looking_for': 'Busco',
      'age': 'Edad',
      'years': 'años',
      'relationship_type': '¿Qué tipo de relación buscas?',
      'country': 'País',
      'city': 'Ciudad',
      'interests': 'Intereses Comunes',
      'advanced_search': '+ Búsqueda Avanzada (opcional)',
      'hide_advanced': 'Ocultar Búsqueda Avanzada',
      'optional_criteria': 'Criterios Opcionales',
      'height': 'Altura',
      'height_cm': 'Altura (cm)',
      'from': 'Desde',
      'to': 'Hasta',
      'has_children': '¿Tiene hijos?',
      'wants_children': '¿Quiere hijos?',
      'education': 'Educación',
      'smoking': '¿Fumador?',
      'drinking': '¿Bebe alcohol?',
      'religion': 'Religión',
      'languages': 'Idiomas hablados',
      'body_type': 'Tipo de cuerpo',
      'relationship_status': 'Estado civil',
      'post_ad': 'Publicar anuncio',
      'my_ads': 'Mis anuncios',
      'title': 'Título',
      'description': 'Descripción',
      'name': 'Nombre',
      'phone': 'Teléfono',
      'photos': 'Fotos',
      'add_photos': 'Añadir fotos',
      'select_gender': 'Seleccionar género',
      'select_relationship_type': 'Seleccionar tipo de relación',
      'male': 'Hombre',
      'female': 'Mujer',
      'non_binary': 'No binario',
      'yes': 'Sí',
      'no': 'No',
      'maybe': 'Quizás',
      'already_have': 'Ya tengo',
      'prefer_not_say': 'Prefiero no decir',
      'high_school': 'Secundaria',
      'college': 'Universidad',
      'masters': 'Máster',
      'phd': 'Doctorado',
      'other': 'Otro',
      'occasionally': 'Ocasionalmente',
      'no_consume': 'No consumo',
      'socially': 'Socialmente',
      'frequently': 'Frecuentemente',
      'athletic': 'Atlético',
      'slim': 'Delgado',
      'average': 'Promedio',
      'curvy': 'Con curvas',
      'plus_size': 'Talla grande',
      'single': 'Soltero(a)',
      'divorced': 'Divorciado(a)',
      'widowed': 'Viudo(a)',
      'orthodox': 'Ortodoxo',
      'catholic': 'Católico',
      'protestant': 'Protestante',
      'muslim': 'Musulmán',
      'buddhist': 'Budista',
      'atheist': 'Ateo',
      'agnostic': 'Agnóstico',
      'change_language': 'Cambiar idioma',
      'language': 'Idioma',
      'romanian': 'Rumano',
      'english': 'Inglés',
      'french': 'Francés',
      'german': 'Alemán',
      'spanish': 'Español',
      'italian': 'Italiano',
      'russian': 'Ruso',
      'hungarian': 'Húngaro',
      'post_matrimonial_ad': 'Publicar Anuncio',
      'my_ads_title': 'Mis Anuncios',
      'ads_posted': 'anuncios publicados',
      'ad_posted': 'anuncio publicado',
      'no_ads_yet': 'Aún no hay anuncios publicados',
      'post_first_ad': '¡Publica tu primer anuncio para encontrar tu pareja perfecta!',
      'post_new_ad': 'Publicar Nuevo Anuncio',
      'find_match': 'Encuentra Tu Pareja',
      'perfect_match_description': 'Encuentra a la persona que te encaja perfectamente basado en compatibilidad real',
      'login_register': 'Iniciar Sesión / Registrarse',
      'no_favorites': 'No hay anuncios guardados',
      'save_favorites': 'Guarda los anuncios que te interesan',
      'no_messages': 'No hay conversaciones',
      'start_messaging': 'Envía un mensaje para comenzar una conversación',
      'unread': 'no leído',
      'unread_plural': 'no leídos',
    },

    // ITALIANO
    'it': {
      'app_name': 'DatingX',
      'welcome': 'Benvenuto',
      'login': 'Accedi',
      'register': 'Registrati',
      'email': 'Email',
      'password': 'Password',
      'confirm_password': 'Conferma password',
      'forgot_password': 'Password dimenticata?',
      'dont_have_account': 'Non hai un account?',
      'already_have_account': 'Hai già un account?',
      'search': 'Cerca',
      'discover': 'Scopri',
      'favorites': 'Le Tue Compatibilità',
      'messages': 'I Tuoi Messaggi',
      'profile': 'Profilo',
      'edit_profile': 'Modifica profilo',
      'logout': 'Esci',
      'save': 'Salva',
      'cancel': 'Annulla',
      'delete': 'Elimina',
      'send': 'Invia',
      'search_perfect_match': 'Trova la tua anima gemella',
      'looking_for': 'Cerco',
      'age': 'Età',
      'years': 'anni',
      'relationship_type': 'Che tipo di relazione cerchi?',
      'country': 'Paese',
      'city': 'Città',
      'interests': 'Interessi Comuni',
      'advanced_search': '+ Ricerca Avanzata (opzionale)',
      'hide_advanced': 'Nascondi Ricerca Avanzata',
      'optional_criteria': 'Criteri Opzionali',
      'height': 'Altezza',
      'height_cm': 'Altezza (cm)',
      'from': 'Da',
      'to': 'A',
      'has_children': 'Ha figli?',
      'wants_children': 'Vuole figli?',
      'education': 'Istruzione',
      'smoking': 'Fumatore?',
      'drinking': 'Beve alcolici?',
      'religion': 'Religione',
      'languages': 'Lingue parlate',
      'body_type': 'Tipo di corporatura',
      'relationship_status': 'Stato civile',
      'post_ad': 'Pubblica annuncio',
      'my_ads': 'I miei annunci',
      'title': 'Titolo',
      'description': 'Descrizione',
      'name': 'Nome',
      'phone': 'Telefono',
      'photos': 'Foto',
      'add_photos': 'Aggiungi foto',
      'select_gender': 'Seleziona il genere',
      'select_relationship_type': 'Seleziona il tipo di relazione',
      'male': 'Uomo',
      'female': 'Donna',
      'non_binary': 'Non binario',
      'yes': 'Sì',
      'no': 'No',
      'maybe': 'Forse',
      'already_have': 'Ho già',
      'prefer_not_say': 'Preferisco non dire',
      'high_school': 'Scuola superiore',
      'college': 'Università',
      'masters': 'Laurea magistrale',
      'phd': 'Dottorato',
      'other': 'Altro',
      'occasionally': 'Occasionalmente',
      'no_consume': 'Non consumo',
      'socially': 'Socialmente',
      'frequently': 'Frequentemente',
      'athletic': 'Atletico',
      'slim': 'Magro',
      'average': 'Medio',
      'curvy': 'Formoso',
      'plus_size': 'Taglia forte',
      'single': 'Single',
      'divorced': 'Divorziato(a)',
      'widowed': 'Vedovo(a)',
      'orthodox': 'Ortodosso',
      'catholic': 'Cattolico',
      'protestant': 'Protestante',
      'muslim': 'Musulmano',
      'buddhist': 'Buddista',
      'atheist': 'Ateo',
      'agnostic': 'Agnostico',
      'change_language': 'Cambia lingua',
      'language': 'Lingua',
      'romanian': 'Rumeno',
      'english': 'Inglese',
      'french': 'Francese',
      'german': 'Tedesco',
      'spanish': 'Spagnolo',
      'italian': 'Italiano',
      'russian': 'Russo',
      'hungarian': 'Ungherese',
      'post_matrimonial_ad': 'Pubblica Annuncio',
      'my_ads_title': 'I Miei Annunci',
      'ads_posted': 'annunci pubblicati',
      'ad_posted': 'annuncio pubblicato',
      'no_ads_yet': 'Nessun annuncio pubblicato ancora',
      'post_first_ad': 'Pubblica il tuo primo annuncio per trovare la tua anima gemella!',
      'post_new_ad': 'Pubblica Nuovo Annuncio',
      'find_match': 'Trova La Tua Anima Gemella',
      'perfect_match_description': 'Trova la persona che ti corrisponde perfettamente basato su compatibilità reale',
      'login_register': 'Accedi / Registrati',
      'no_favorites': 'Nessun annuncio salvato',
      'save_favorites': 'Salva gli annunci che ti interessano',
      'no_messages': 'Nessuna conversazione',
      'start_messaging': 'Invia un messaggio per iniziare una conversazione',
      'unread': 'non letto',
      'unread_plural': 'non letti',
    },

    // РУССКИЙ
    'ru': {
      'app_name': 'DatingX',
      'welcome': 'Добро пожаловать',
      'login': 'Войти',
      'register': 'Зарегистрироваться',
      'email': 'Электронная почта',
      'password': 'Пароль',
      'confirm_password': 'Подтвердите пароль',
      'forgot_password': 'Забыли пароль?',
      'dont_have_account': 'Нет аккаунта?',
      'already_have_account': 'Уже есть аккаунт?',
      'search': 'Поиск',
      'discover': 'Открыть',
      'favorites': 'Ваши Совпадения',
      'messages': 'Ваши Сообщения',
      'profile': 'Профиль',
      'edit_profile': 'Редактировать профиль',
      'logout': 'Выйти',
      'save': 'Сохранить',
      'cancel': 'Отмена',
      'delete': 'Удалить',
      'send': 'Отправить',
      'search_perfect_match': 'Найдите свою идеальную пару',
      'looking_for': 'Ищу',
      'age': 'Возраст',
      'years': 'лет',
      'relationship_type': 'Какой тип отношений вы ищете?',
      'country': 'Страна',
      'city': 'Город',
      'interests': 'Общие интересы',
      'advanced_search': '+ Расширенный поиск (необязательно)',
      'hide_advanced': 'Скрыть расширенный поиск',
      'optional_criteria': 'Необязательные критерии',
      'height': 'Рост',
      'height_cm': 'Рост (см)',
      'from': 'От',
      'to': 'До',
      'has_children': 'Есть дети?',
      'wants_children': 'Хочет детей?',
      'education': 'Образование',
      'smoking': 'Курящий?',
      'drinking': 'Употребляет алкоголь?',
      'religion': 'Религия',
      'languages': 'Языки',
      'body_type': 'Тип телосложения',
      'relationship_status': 'Семейное положение',
      'post_ad': 'Разместить объявление',
      'my_ads': 'Мои объявления',
      'title': 'Заголовок',
      'description': 'Описание',
      'name': 'Имя',
      'phone': 'Телефон',
      'photos': 'Фотографии',
      'add_photos': 'Добавить фото',
      'select_gender': 'Выберите пол',
      'select_relationship_type': 'Выберите тип отношений',
      'male': 'Мужчина',
      'female': 'Женщина',
      'non_binary': 'Небинарный',
      'yes': 'Да',
      'no': 'Нет',
      'maybe': 'Может быть',
      'already_have': 'Уже есть',
      'prefer_not_say': 'Предпочитаю не говорить',
      'high_school': 'Средняя школа',
      'college': 'Колледж',
      'masters': 'Магистратура',
      'phd': 'Докторская степень',
      'other': 'Другое',
      'occasionally': 'Иногда',
      'no_consume': 'Не употребляю',
      'socially': 'В компании',
      'frequently': 'Часто',
      'athletic': 'Атлетический',
      'slim': 'Стройный',
      'average': 'Средний',
      'curvy': 'С формами',
      'plus_size': 'Большой размер',
      'single': 'Не женат/не замужем',
      'divorced': 'В разводе',
      'widowed': 'Вдовец/Вдова',
      'orthodox': 'Православный',
      'catholic': 'Католик',
      'protestant': 'Протестант',
      'muslim': 'Мусульманин',
      'buddhist': 'Буддист',
      'atheist': 'Атеист',
      'agnostic': 'Агностик',
      'change_language': 'Изменить язык',
      'language': 'Язык',
      'romanian': 'Румынский',
      'english': 'Английский',
      'french': 'Французский',
      'german': 'Немецкий',
      'spanish': 'Испанский',
      'italian': 'Итальянский',
      'russian': 'Русский',
      'hungarian': 'Венгерский',
      'post_matrimonial_ad': 'Разместить Объявление',
      'my_ads_title': 'Мои Объявления',
      'ads_posted': 'объявлений размещено',
      'ad_posted': 'объявление размещено',
      'no_ads_yet': 'Пока нет объявлений',
      'post_first_ad': 'Разместите свое первое объявление, чтобы найти свою идеальную пару!',
      'post_new_ad': 'Разместить Новое Объявление',
      'find_match': 'Найти Свою Пару',
      'perfect_match_description': 'Найдите человека, который идеально вам подходит на основе реальной совместимости',
      'login_register': 'Войти / Зарегистрироваться',
      'no_favorites': 'Нет сохраненных объявлений',
      'save_favorites': 'Сохраняйте объявления, которые вас интересуют',
      'no_messages': 'Нет разговоров',
      'start_messaging': 'Отправьте сообщение, чтобы начать разговор',
      'unread': 'непрочитанное',
      'unread_plural': 'непрочитанных',
    },

    // MAGYAR
    'hu': {
      'app_name': 'DatingX',
      'welcome': 'Üdvözöljük',
      'login': 'Bejelentkezés',
      'register': 'Regisztráció',
      'email': 'E-mail',
      'password': 'Jelszó',
      'confirm_password': 'Jelszó megerősítése',
      'forgot_password': 'Elfelejtette jelszavát?',
      'dont_have_account': 'Nincs fiókja?',
      'already_have_account': 'Már van fiókja?',
      'search': 'Keresés',
      'discover': 'Felfedezés',
      'favorites': 'Egyezéseid',
      'messages': 'Üzeneteid',
      'profile': 'Profil',
      'edit_profile': 'Profil szerkesztése',
      'logout': 'Kijelentkezés',
      'save': 'Mentés',
      'cancel': 'Mégse',
      'delete': 'Törlés',
      'send': 'Küldés',
      'search_perfect_match': 'Találd meg a tökéletes párod',
      'looking_for': 'Keresem',
      'age': 'Életkor',
      'years': 'év',
      'relationship_type': 'Milyen kapcsolatot keresel?',
      'country': 'Ország',
      'city': 'Város',
      'interests': 'Közös érdeklődési körök',
      'advanced_search': '+ Speciális keresés (opcionális)',
      'hide_advanced': 'Speciális keresés elrejtése',
      'optional_criteria': 'Opcionális kritériumok',
      'height': 'Magasság',
      'height_cm': 'Magasság (cm)',
      'from': 'Tól',
      'to': 'Ig',
      'has_children': 'Van gyermeke?',
      'wants_children': 'Szeretne gyermeket?',
      'education': 'Végzettség',
      'smoking': 'Dohányzik?',
      'drinking': 'Alkoholt fogyaszt?',
      'religion': 'Vallás',
      'languages': 'Beszélt nyelvek',
      'body_type': 'Testalkat',
      'relationship_status': 'Kapcsolati státusz',
      'post_ad': 'Hirdetés feladása',
      'my_ads': 'Hirdetéseim',
      'title': 'Cím',
      'description': 'Leírás',
      'name': 'Név',
      'phone': 'Telefon',
      'photos': 'Fényképek',
      'add_photos': 'Fényképek hozzáadása',
      'select_gender': 'Válassz nemet',
      'select_relationship_type': 'Válassz kapcsolattípust',
      'male': 'Férfi',
      'female': 'Nő',
      'non_binary': 'Nem-bináris',
      'yes': 'Igen',
      'no': 'Nem',
      'maybe': 'Talán',
      'already_have': 'Már van',
      'prefer_not_say': 'Inkább nem mondom',
      'high_school': 'Középiskola',
      'college': 'Főiskola',
      'masters': 'Mester',
      'phd': 'PhD',
      'other': 'Egyéb',
      'occasionally': 'Alkalmanként',
      'no_consume': 'Nem fogyasztok',
      'socially': 'Társaságban',
      'frequently': 'Gyakran',
      'athletic': 'Sportos',
      'slim': 'Karcsú',
      'average': 'Átlagos',
      'curvy': 'Gömbölyded',
      'plus_size': 'Nagy méret',
      'single': 'Egyedülálló',
      'divorced': 'Elvált',
      'widowed': 'Özvegy',
      'orthodox': 'Ortodox',
      'catholic': 'Katolikus',
      'protestant': 'Protestáns',
      'muslim': 'Muszlim',
      'buddhist': 'Buddhista',
      'atheist': 'Ateista',
      'agnostic': 'Agnosztikus',
      'change_language': 'Nyelv váltása',
      'language': 'Nyelv',
      'romanian': 'Román',
      'english': 'Angol',
      'french': 'Francia',
      'german': 'Német',
      'spanish': 'Spanyol',
      'italian': 'Olasz',
      'russian': 'Orosz',
      'hungarian': 'Magyar',
      'post_matrimonial_ad': 'Hirdetés Feladása',
      'my_ads_title': 'Hirdetéseim',
      'ads_posted': 'hirdetés feladása',
      'ad_posted': 'hirdetés feladva',
      'no_ads_yet': 'Még nincsenek hirdetések',
      'post_first_ad': 'Add fel az első hirdetésed, hogy megtaláld a tökéletes párod!',
      'post_new_ad': 'Új Hirdetés Feladása',
      'find_match': 'Találd Meg Párod',
      'perfect_match_description': 'Találd meg az életed párját valódi kompatibilitás alapján',
      'login_register': 'Bejelentkezés / Regisztráció',
      'no_favorites': 'Nincsenek mentett hirdetések',
      'save_favorites': 'Mentsd el az érdekes hirdetéseket',
      'no_messages': 'Nincsenek beszélgetések',
      'start_messaging': 'Küldj egy üzenetet a beszélgetés indításához',
      'unread': 'olvasatlan',
      'unread_plural': 'olvasatlan',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['ro', 'en', 'fr', 'de', 'es', 'it', 'ru', 'hu'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
